export enum CharClass {
    cleric = 'cleric',
    dwarf = 'dwarf',
    elf = 'elf',
    fighter = 'fighter',
    halfling = 'halfling',
    magicUser = 'Magic-User',
    thief = 'thief',
    normalHuman = 'normal human',
    // OSE Advanced
    acrobat = 'acrobat',
    assassin = 'assassin',
    barbarian = 'barbarian',
    bard = 'bard',
    drow = 'drow',
    druid = 'druid',
    duergar = 'duergar',
    gnome = 'gnome',
    half_elf = 'Half-Elf',
    half_orc = 'Half-Orc',
    illusionist = 'illusionist',
    knight = 'knight',
    paladin = 'paladin',
    ranger = 'ranger',
    svirfneblin = 'svirfneblin',
}
